version: "3.9"

services:
  app:
    image: task-manager
    build: .
    container_name: task-manager
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:80/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5


  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:4
    depends_on:
      db:
        condition: service_healthy
    command: ["-path=/migrations", "-database", "postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    restart: "no"

volumes:
  db_data:
